// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Container: typeof import('./src/components/Container/index.vue')['default']
    Contaioner: typeof import('./src/components/Contaioner/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElIconDocument: typeof import('element-plus/es')['ElIconDocument']
    ElIconEdit: typeof import('element-plus/es')['ElIconEdit']
    ElIconMenu: typeof import('element-plus/es')['ElIconMenu']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSelector: typeof import('element-plus/es')['ElSelector']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconSelector: typeof import('./src/components/IconSelector/index.vue')['default']
    Inde: typeof import('./src/components/myContainer/src/navHeader/inde.vue')['default']
    MyIcon: typeof import('./src/components/myIcon/index.vue')['default']
    NavHeader: typeof import('./src/components/CustomContainer/src/navHeader/index.vue')['default']
    NavSide: typeof import('./src/components/CustomContainer/src/navSide/index.vue')['default']
    Src: typeof import('./src/components/CustomContainer/src/index.vue')['default']
  }
}

export { }
