// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CitySelector: typeof import('./src/components/CitySelector/CitySelector.vue')['default']
    Container: typeof import('./src/components/Container/index.vue')['default']
    Contaioner: typeof import('./src/components/Contaioner/index.vue')['default']
    DateSelector: typeof import('./src/components/DateSelector/DateSelector.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElIconDocument: typeof import('element-plus/es')['ElIconDocument']
    ElIconEdit: typeof import('element-plus/es')['ElIconEdit']
    ElIconMenu: typeof import('element-plus/es')['ElIconMenu']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSelector: typeof import('element-plus/es')['ElSelector']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Form: typeof import('./src/components/Form/Form.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconSelector: typeof import('./src/components/IconSelector/IconSelector.vue')['default']
    Inde: typeof import('./src/components/myContainer/src/navHeader/inde.vue')['default']
    List: typeof import('./src/components/List/List.vue')['default']
    LocationSelector: typeof import('./src/components/LocationSelector/LocationSelector.vue')['default']
    Menu: typeof import('./src/components/Menu/Menu.vue')['default']
    MyIcon: typeof import('./src/components/myIcon/index.vue')['default']
    NavHeader: typeof import('./src/components/CustomContainer/src/navHeader/index.vue')['default']
    NavSide: typeof import('./src/components/CustomContainer/src/navSide/index.vue')['default']
    Notification: typeof import('./src/components/Notification/Notification.vue')['default']
    Src: typeof import('./src/components/CustomContainer/src/index.vue')['default']
  }
}

export { }
